insert into products (id, name, price, description) values (1, 'Bread Base - Toscano', '$4.32', 'synergize impactful mindshare');
insert into products (id, name, price, description) values (2, 'Cheese - Cheddar With Claret', '$9.09', 'incentivize efficient deliverables');
insert into products (id, name, price, description) values (3, 'Flour - Teff', '$4.77', 'morph front-end ROI');
insert into products (id, name, price, description) values (4, 'Jameson Irish Whiskey', '$8.80', 'scale real-time synergies');
insert into products (id, name, price, description) values (5, 'Kippers - Smoked', '$6.78', 'incentivize magnetic experiences');
insert into products (id, name, price, description) values (6, 'Oneshot Automatic Soap System', '$5.22', 'transition plug-and-play infomediaries');
insert into products (id, name, price, description) values (7, 'Lamb - Leg, Diced', '$2.21', 'target 24/365 e-business');
insert into products (id, name, price, description) values (8, 'Arrowroot', '$3.36', 'engineer holistic relationships');
insert into products (id, name, price, description) values (9, 'Mustard - Individual Pkg', '$2.05', 'expedite global eyeballs');
insert into products (id, name, price, description) values (10, 'The Pop Shoppe - Lime Rickey', '$4.56', 'unleash proactive bandwidth');
insert into products (id, name, price, description) values (11, 'Tuna - Sushi Grade', '$8.65', 'synergize leading-edge bandwidth');
insert into products (id, name, price, description) values (12, 'Water - Spring Water 500ml', '$9.04', 'whiteboard ubiquitous eyeballs');
insert into products (id, name, price, description) values (13, 'Icecream - Dstk Cml And Fdg', '$4.35', 'expedite holistic relationships');
insert into products (id, name, price, description) values (14, 'Bay Leaf Ground', '$4.17', 'evolve out-of-the-box mindshare');
insert into products (id, name, price, description) values (15, 'Cookies - Oreo, 4 Pack', '$4.64', 'engineer synergistic portals');
insert into products (id, name, price, description) values (16, 'Flour - Bran, Red', '$9.61', 'transform sexy content');
insert into products (id, name, price, description) values (17, 'Bok Choy - Baby', '$9.62', 'expedite virtual interfaces');
insert into products (id, name, price, description) values (18, 'Container Clear 8 Oz', '$2.12', 'seize dot-com e-commerce');
insert into products (id, name, price, description) values (19, 'Bread Roll Foccacia', '$5.87', 'implement enterprise action-items');
insert into products (id, name, price, description) values (20, 'Olives - Stuffed', '$1.88', 'maximize next-generation interfaces');
insert into products (id, name, price, description) values (21, 'Apricots - Dried', '$6.30', 'deliver world-class markets');
insert into products (id, name, price, description) values (22, 'Towel Dispenser', '$6.08', 'empower open-source schemas');
insert into products (id, name, price, description) values (23, 'Beets', '$4.57', 'drive scalable relationships');
insert into products (id, name, price, description) values (24, 'Orange - Tangerine', '$3.36', 'orchestrate wireless networks');
insert into products (id, name, price, description) values (25, 'Puree - Pear', '$1.60', 'disintermediate B2B supply-chains');
insert into products (id, name, price, description) values (26, 'Smoked Tongue', '$2.03', 'leverage e-business models');
insert into products (id, name, price, description) values (27, 'Pecan Raisin - Tarts', '$1.90', 'transition vertical web-readiness');
insert into products (id, name, price, description) values (28, 'Container - Clear 16 Oz', '$6.28', 'whiteboard mission-critical users');
insert into products (id, name, price, description) values (29, 'Beef - Tenderloin - Aa', '$4.48', 'seize collaborative architectures');
insert into products (id, name, price, description) values (30, 'Bar - Sweet And Salty Chocolate', '$9.48', 'innovate vertical markets');
insert into products (id, name, price, description) values (31, 'Steamers White', '$1.97', 'envisioneer collaborative communities');
insert into products (id, name, price, description) values (32, 'Pea - Snow', '$6.41', 'synthesize user-centric web-readiness');
insert into products (id, name, price, description) values (33, 'Lidsoupcont Rp12dn', '$1.71', 'synergize B2B functionalities');
insert into products (id, name, price, description) values (34, 'Durian Fruit', '$7.28', 'scale rich niches');
insert into products (id, name, price, description) values (35, 'Buffalo - Short Rib Fresh', '$5.30', 'innovate back-end web services');
insert into products (id, name, price, description) values (36, 'Haggis', '$7.04', 'redefine real-time ROI');
insert into products (id, name, price, description) values (37, 'Pasta - Ravioli', '$8.68', 'target strategic mindshare');
insert into products (id, name, price, description) values (38, 'Ezy Change Mophandle', '$4.69', 'engineer leading-edge applications');
insert into products (id, name, price, description) values (39, 'Bread - Raisin', '$3.16', 'whiteboard clicks-and-mortar applications');
insert into products (id, name, price, description) values (40, 'Sausage - Meat', '$5.44', 'optimize e-business eyeballs');
insert into products (id, name, price, description) values (41, 'Beef - Montreal Smoked Brisket', '$8.01', 'optimize sticky content');
insert into products (id, name, price, description) values (42, 'Pork Salted Bellies', '$1.35', 'incubate frictionless functionalities');
insert into products (id, name, price, description) values (43, 'Fish - Base, Bouillion', '$9.47', 'revolutionize seamless solutions');
insert into products (id, name, price, description) values (44, 'Cheese - Brie, Triple Creme', '$5.07', 'transition sticky synergies');
insert into products (id, name, price, description) values (45, 'Beef - Chuck, Boneless', '$7.37', 'grow collaborative models');
insert into products (id, name, price, description) values (46, 'Wine - Redchard Merritt', '$2.81', 'monetize rich systems');
insert into products (id, name, price, description) values (47, 'Coffee - Irish Cream', '$7.19', 'matrix plug-and-play metrics');
insert into products (id, name, price, description) values (48, 'Veal - Tenderloin, Untrimmed', '$4.98', 'matrix integrated models');
insert into products (id, name, price, description) values (49, 'Trueblue - Blueberry 12x473ml', '$1.22', 'mesh frictionless content');
insert into products (id, name, price, description) values (50, 'Papadam', '$5.53', 'deliver web-enabled markets');
insert into products (id, name, price, description) values (51, 'Oil - Canola', '$5.77', 'orchestrate interactive architectures');
insert into products (id, name, price, description) values (52, 'Tomatoes - Orange', '$8.96', 'productize bleeding-edge solutions');
insert into products (id, name, price, description) values (53, 'Onions - Cippolini', '$9.39', 'expedite granular systems');
insert into products (id, name, price, description) values (54, 'Pasta - Bauletti, Chicken White', '$5.05', 'visualize open-source metrics');
insert into products (id, name, price, description) values (55, 'Sobe - Tropical Energy', '$9.04', 'incubate 24/7 markets');
insert into products (id, name, price, description) values (56, 'Chips Potato Salt Vinegar 43g', '$9.24', 'utilize visionary markets');
insert into products (id, name, price, description) values (57, 'Carbonated Water - Lemon Lime', '$7.43', 'morph viral systems');
insert into products (id, name, price, description) values (58, 'Star Fruit', '$8.73', 'recontextualize cutting-edge paradigms');
insert into products (id, name, price, description) values (59, 'Muffin - Mix - Mango Sour Cherry', '$6.44', 'leverage dot-com action-items');
insert into products (id, name, price, description) values (60, 'Muffin Hinge - 211n', '$9.96', 'repurpose interactive action-items');
insert into products (id, name, price, description) values (61, 'Pie Pecan', '$2.09', 'expedite dynamic synergies');
insert into products (id, name, price, description) values (62, 'Beef - Rib Roast, Cap On', '$4.35', 'e-enable bricks-and-clicks eyeballs');
insert into products (id, name, price, description) values (63, 'Ham - Smoked, Bone - In', '$6.42', 'expedite bricks-and-clicks interfaces');
insert into products (id, name, price, description) values (64, 'Nut - Pumpkin Seeds', '$1.12', 'transition magnetic convergence');
insert into products (id, name, price, description) values (65, 'Tea - Herbal Orange Spice', '$8.15', 'morph ubiquitous schemas');
insert into products (id, name, price, description) values (66, 'Tea - Lemon Scented', '$9.70', 'synthesize open-source portals');
insert into products (id, name, price, description) values (67, 'Emulsifier', '$7.98', 'synthesize interactive experiences');
insert into products (id, name, price, description) values (68, 'Grapefruit - Pink', '$7.00', 'optimize rich deliverables');
insert into products (id, name, price, description) values (69, 'Tomatoes - Vine Ripe, Red', '$3.88', 'architect intuitive architectures');
insert into products (id, name, price, description) values (70, 'Soup - Cream Of Broccoli', '$3.88', 'orchestrate e-business vortals');
insert into products (id, name, price, description) values (71, 'Oyster - In Shell', '$1.80', 'architect holistic systems');
insert into products (id, name, price, description) values (72, 'Cinnamon - Stick', '$2.42', 'integrate value-added niches');
insert into products (id, name, price, description) values (73, 'Cheese - Montery Jack', '$2.90', 'implement scalable convergence');
insert into products (id, name, price, description) values (74, 'Wine - Stoneliegh Sauvignon', '$3.16', 'drive enterprise architectures');
insert into products (id, name, price, description) values (75, 'Shallots', '$2.88', 'matrix web-enabled channels');
insert into products (id, name, price, description) values (76, 'Coffee - Decafenated', '$1.39', 'implement distributed metrics');
insert into products (id, name, price, description) values (77, 'Loaf Pan - 2 Lb, Foil', '$4.42', 'leverage visionary relationships');
insert into products (id, name, price, description) values (78, 'Salt And Pepper Mix - Black', '$6.83', 'orchestrate end-to-end niches');
insert into products (id, name, price, description) values (79, 'Coffee - Dark Roast', '$7.18', 'extend enterprise e-services');
insert into products (id, name, price, description) values (80, 'Paper Cocktail Umberlla 80 - 180', '$3.59', 'implement magnetic e-services');
insert into products (id, name, price, description) values (81, 'Cheese - Cheddar, Mild', '$9.60', 'empower 24/365 communities');
insert into products (id, name, price, description) values (82, 'Beans - Fine', '$1.47', 'embrace end-to-end communities');
insert into products (id, name, price, description) values (83, 'Potatoes - Idaho 100 Count', '$5.65', 'repurpose open-source supply-chains');
insert into products (id, name, price, description) values (84, 'Ecolab - Orange Frc, Cleaner', '$4.23', 'implement transparent markets');
insert into products (id, name, price, description) values (85, 'Liners - Baking Cups', '$9.34', 'optimize global platforms');
insert into products (id, name, price, description) values (86, 'Cinnamon Rolls', '$3.06', 'target seamless e-markets');
insert into products (id, name, price, description) values (87, 'Pike - Frozen Fillet', '$8.59', 'streamline front-end interfaces');
insert into products (id, name, price, description) values (88, 'Pepper - Red Chili', '$7.52', 'synthesize end-to-end users');
insert into products (id, name, price, description) values (89, 'Basil - Pesto Sauce', '$9.95', 'implement seamless eyeballs');
insert into products (id, name, price, description) values (90, 'Scallops - Live In Shell', '$3.71', 'embrace sexy channels');
insert into products (id, name, price, description) values (91, 'Doilies - 10, Paper', '$6.12', 'deliver rich solutions');
insert into products (id, name, price, description) values (92, 'Shark - Loin', '$1.95', 'matrix B2B platforms');
insert into products (id, name, price, description) values (93, 'Beef - Texas Style Burger', '$3.47', 'empower revolutionary architectures');
insert into products (id, name, price, description) values (94, 'Chef Hat 20cm', '$4.57', 'synergize user-centric infrastructures');
insert into products (id, name, price, description) values (95, 'Shrimp - Baby, Warm Water', '$4.76', 'incentivize customized channels');
insert into products (id, name, price, description) values (96, 'Chicken Breast Wing On', '$4.89', 'revolutionize ubiquitous web-readiness');
insert into products (id, name, price, description) values (97, 'Snapple - Mango Maddness', '$4.61', 'expedite B2B e-tailers');
insert into products (id, name, price, description) values (98, 'Ostrich - Prime Cut', '$4.87', 'scale open-source users');
insert into products (id, name, price, description) values (99, 'Beef - Tongue, Fresh', '$4.71', 'harness revolutionary content');
insert into products (id, name, price, description) values (100, 'Figs', '$2.16', 'visualize rich web-readiness');
insert into products (id, name, price, description) values (101, 'Island Oasis - Banana Daiquiri', '$3.30', 'monetize dynamic channels');
insert into products (id, name, price, description) values (102, 'Oregano - Dry, Rubbed', '$1.09', 'strategize magnetic web services');
insert into products (id, name, price, description) values (103, 'Southern Comfort', '$6.07', 'harness killer e-services');
insert into products (id, name, price, description) values (104, 'Wine - Soave Folonari', '$7.01', 'synthesize virtual mindshare');
insert into products (id, name, price, description) values (105, 'Dc - Frozen Momji', '$6.35', 'brand vertical e-markets');
insert into products (id, name, price, description) values (106, 'Ecolab - Lime - A - Way 4/4 L', '$9.62', 'seize mission-critical metrics');
insert into products (id, name, price, description) values (107, 'Pork - Bones', '$5.13', 'deploy distributed applications');
insert into products (id, name, price, description) values (108, 'Leeks - Large', '$1.30', 'innovate granular solutions');
insert into products (id, name, price, description) values (109, 'Cheese - St. Andre', '$7.09', 'evolve bricks-and-clicks bandwidth');
insert into products (id, name, price, description) values (110, 'Wine - Fat Bastard Merlot', '$2.97', 'productize compelling infomediaries');
insert into products (id, name, price, description) values (111, 'Milk Powder', '$4.08', 'e-enable killer deliverables');
insert into products (id, name, price, description) values (112, 'Pepper - Orange', '$2.14', 'optimize turn-key e-markets');
insert into products (id, name, price, description) values (113, 'Bread - White, Sliced', '$9.11', 'morph proactive markets');
insert into products (id, name, price, description) values (114, 'Mushroom - Trumpet, Dry', '$6.16', 'benchmark clicks-and-mortar deliverables');
insert into products (id, name, price, description) values (115, 'Glove - Cutting', '$8.38', 'envisioneer user-centric infrastructures');
insert into products (id, name, price, description) values (116, 'Seedlings - Buckwheat, Organic', '$9.61', 'aggregate real-time paradigms');
insert into products (id, name, price, description) values (117, 'Muffin Mix - Morning Glory', '$5.71', 'visualize scalable interfaces');
insert into products (id, name, price, description) values (118, 'Beans - Black Bean, Dry', '$5.24', 'enhance front-end channels');
insert into products (id, name, price, description) values (119, 'Apple - Custard', '$2.76', 'extend e-business web services');
insert into products (id, name, price, description) values (120, 'Salsify, Organic', '$7.32', 'benchmark visionary interfaces');
insert into products (id, name, price, description) values (121, 'Beer - Upper Canada Light', '$2.16', 'implement dynamic convergence');
insert into products (id, name, price, description) values (122, 'English Muffin', '$2.35', 'syndicate scalable systems');
insert into products (id, name, price, description) values (123, 'Pepper - White, Ground', '$4.44', 'scale strategic content');
insert into products (id, name, price, description) values (124, 'Food Colouring - Green', '$1.30', 'target leading-edge content');
insert into products (id, name, price, description) values (125, 'Vinegar - Cider', '$1.12', 'morph cross-media e-business');
insert into products (id, name, price, description) values (126, 'Veal - Inside Round / Top, Lean', '$9.43', 'reintermediate vertical e-markets');
insert into products (id, name, price, description) values (127, 'Lamb - Shoulder, Boneless', '$6.81', 'visualize front-end solutions');
insert into products (id, name, price, description) values (128, 'Gelatine Leaves - Bulk', '$2.20', 'aggregate plug-and-play initiatives');
insert into products (id, name, price, description) values (129, 'Kiwi', '$6.49', 'iterate efficient e-tailers');
insert into products (id, name, price, description) values (130, 'Muffin Mix - Banana Nut', '$2.72', 'implement clicks-and-mortar e-markets');
insert into products (id, name, price, description) values (131, 'Soup Campbells Turkey Veg.', '$8.21', 'deliver real-time initiatives');
insert into products (id, name, price, description) values (132, 'Scallops - 20/30', '$1.14', 'incentivize 24/7 platforms');
insert into products (id, name, price, description) values (133, 'Coffee - Beans, Whole', '$2.56', 'grow customized web services');
insert into products (id, name, price, description) values (134, 'Leeks - Large', '$1.20', 'engineer collaborative synergies');
insert into products (id, name, price, description) values (135, 'Ocean Spray - Ruby Red', '$1.22', 'strategize next-generation e-business');
insert into products (id, name, price, description) values (136, 'Contreau', '$8.17', 'target next-generation action-items');
insert into products (id, name, price, description) values (137, 'Beans - Butter Lrg Lima', '$6.74', 'e-enable vertical systems');
insert into products (id, name, price, description) values (138, 'Wine - Chianti Classico Riserva', '$6.85', 'implement real-time mindshare');
insert into products (id, name, price, description) values (139, 'Coffee - Espresso', '$9.16', 'envisioneer distributed e-markets');
insert into products (id, name, price, description) values (140, 'Pasta - Linguini, Dry', '$5.63', 'seize collaborative web services');
insert into products (id, name, price, description) values (141, 'Sauce - Sesame Thai Dressing', '$5.66', 'benchmark transparent schemas');
insert into products (id, name, price, description) values (142, 'Towel Multifold', '$4.40', 'transform sexy solutions');
insert into products (id, name, price, description) values (143, 'Containter - 3oz Microwave Rect.', '$6.14', 'innovate integrated niches');
insert into products (id, name, price, description) values (144, 'Muffin - Carrot Individual Wrap', '$7.24', 'drive granular markets');
insert into products (id, name, price, description) values (145, 'Sour Puss Raspberry', '$6.99', 'optimize granular functionalities');
insert into products (id, name, price, description) values (146, 'Wine La Vielle Ferme Cote Du', '$3.12', 'incentivize transparent communities');
insert into products (id, name, price, description) values (147, 'Mortadella', '$1.80', 'engineer vertical ROI');
insert into products (id, name, price, description) values (148, 'Bread - Bistro Sour', '$3.19', 'incentivize rich architectures');
insert into products (id, name, price, description) values (149, 'Sausage - Blood Pudding', '$7.62', 'e-enable cross-media e-markets');
insert into products (id, name, price, description) values (150, 'Munchies Honey Sweet Trail Mix', '$4.50', 'synthesize virtual e-services');
insert into products (id, name, price, description) values (151, 'Wine - Periguita Fonseca', '$3.73', 'redefine enterprise models');
insert into products (id, name, price, description) values (152, 'Truffle Cups - White Paper', '$4.33', 'synergize cross-media mindshare');
insert into products (id, name, price, description) values (153, 'Tea Peppermint', '$5.34', 'transition one-to-one technologies');
insert into products (id, name, price, description) values (154, 'Island Oasis - Pina Colada', '$1.11', 'reintermediate scalable paradigms');
insert into products (id, name, price, description) values (155, 'Ice Cream Bar - Hagen Daz', '$9.94', 'architect turn-key experiences');
insert into products (id, name, price, description) values (156, 'Wine - Barbera Alba Doc 2001', '$1.07', 'incentivize cross-platform action-items');
insert into products (id, name, price, description) values (157, 'Soup - Campbells, Creamy', '$4.30', 'whiteboard back-end infomediaries');
insert into products (id, name, price, description) values (158, 'Cake Sheet Combo Party Pack', '$5.36', 'drive scalable technologies');
insert into products (id, name, price, description) values (159, 'Bagelers - Cinn / Brown', '$8.04', 'recontextualize cross-platform convergence');
insert into products (id, name, price, description) values (160, 'Cabbage - Nappa', '$8.19', 'repurpose vertical mindshare');
insert into products (id, name, price, description) values (161, 'Juice - Ocean Spray Kiwi', '$6.80', 'scale real-time networks');
insert into products (id, name, price, description) values (162, 'Rosemary - Fresh', '$1.01', 'repurpose cross-platform channels');
insert into products (id, name, price, description) values (163, 'Doilies - 5, Paper', '$3.32', 'empower vertical e-tailers');
insert into products (id, name, price, description) values (164, 'Coconut - Whole', '$3.65', 'transform seamless schemas');
insert into products (id, name, price, description) values (165, 'Bar Bran Honey Nut', '$6.92', 'optimize collaborative web-readiness');
insert into products (id, name, price, description) values (166, 'Everfresh Products', '$5.99', 'empower rich e-tailers');
insert into products (id, name, price, description) values (167, 'Fond - Chocolate', '$9.33', 'matrix sexy schemas');
insert into products (id, name, price, description) values (168, 'Ecolab Silver Fusion', '$1.32', 'disintermediate 24/365 action-items');
insert into products (id, name, price, description) values (169, 'Soda Water - Club Soda, 355 Ml', '$6.58', 'monetize value-added methodologies');
insert into products (id, name, price, description) values (170, 'Soup - Campbells Tomato Ravioli', '$5.34', 'deliver next-generation infomediaries');
insert into products (id, name, price, description) values (171, 'Pasta - Fett Alfredo, Single Serve', '$2.24', 'evolve proactive mindshare');
insert into products (id, name, price, description) values (172, 'Dried Cranberries', '$3.80', 'engineer proactive relationships');
insert into products (id, name, price, description) values (173, 'Pie Filling - Cherry', '$2.30', 'orchestrate visionary infomediaries');
insert into products (id, name, price, description) values (174, 'Lamb - Shoulder, Boneless', '$9.92', 'deploy collaborative e-markets');
insert into products (id, name, price, description) values (175, 'Bread - Burger', '$6.91', 'expedite dot-com bandwidth');
insert into products (id, name, price, description) values (176, 'Gherkin - Sour', '$7.89', 'transform intuitive architectures');
insert into products (id, name, price, description) values (177, 'Wine - White, Mosel Gold', '$8.97', 'streamline real-time networks');
insert into products (id, name, price, description) values (178, 'Wine - Sherry Dry Sack, William', '$1.47', 'incentivize B2C infrastructures');
insert into products (id, name, price, description) values (179, 'Vinegar - Rice', '$4.82', 'reinvent B2B web-readiness');
insert into products (id, name, price, description) values (180, 'Turkey - Breast, Boneless Sk On', '$7.84', 'synergize efficient eyeballs');
insert into products (id, name, price, description) values (181, 'Veal - Bones', '$4.78', 'exploit bricks-and-clicks solutions');
insert into products (id, name, price, description) values (182, 'Guava', '$3.37', 'architect one-to-one users');
insert into products (id, name, price, description) values (183, 'Cheese - Victor Et Berthold', '$6.20', 'orchestrate visionary networks');
insert into products (id, name, price, description) values (184, 'Eel Fresh', '$8.91', 'unleash plug-and-play e-tailers');
insert into products (id, name, price, description) values (185, 'Pork - Loin, Boneless', '$1.77', 'unleash best-of-breed ROI');
insert into products (id, name, price, description) values (186, 'Pepper - Sorrano', '$4.08', 'maximize mission-critical deliverables');
insert into products (id, name, price, description) values (187, 'Bagelers - Cinn / Brown', '$3.42', 'benchmark 24/365 synergies');
insert into products (id, name, price, description) values (188, 'Nut - Almond, Blanched, Ground', '$1.90', 'matrix one-to-one ROI');
insert into products (id, name, price, description) values (189, 'Icecream - Dibs', '$8.66', 'exploit revolutionary users');
insert into products (id, name, price, description) values (190, 'Tart - Raisin And Pecan', '$5.58', 'drive synergistic deliverables');
insert into products (id, name, price, description) values (191, 'Pail - 4l White, With Handle', '$8.11', 'drive plug-and-play schemas');
insert into products (id, name, price, description) values (192, 'Coffee - Almond Amaretto', '$8.14', 'benchmark B2B interfaces');
insert into products (id, name, price, description) values (193, 'Juice - Pineapple, 48 Oz', '$2.71', 'synthesize ubiquitous networks');
insert into products (id, name, price, description) values (194, 'Bagelers - Cinn / Brown', '$3.27', 'utilize end-to-end networks');
insert into products (id, name, price, description) values (195, 'Juice - Cranberry 284ml', '$6.22', 'aggregate bleeding-edge mindshare');
insert into products (id, name, price, description) values (196, 'Flour - So Mix Cake White', '$3.65', 'evolve web-enabled networks');
insert into products (id, name, price, description) values (197, 'Miso Paste White', '$5.70', 'envisioneer 24/7 architectures');
insert into products (id, name, price, description) values (198, 'Wine - Niagara,vqa Reisling', '$9.84', 'enhance value-added ROI');
insert into products (id, name, price, description) values (199, 'Nantucket Orange Juice', '$5.78', 'envisioneer bleeding-edge web-readiness');
insert into products (id, name, price, description) values (200, 'Wine - Red, Gamay Noir', '$7.40', 'monetize customized methodologies');
insert into products (id, name, price, description) values (201, 'Tomatoes - Vine Ripe, Red', '$8.66', 'orchestrate impactful partnerships');
insert into products (id, name, price, description) values (202, 'Sausage - Meat', '$6.87', 'transform bleeding-edge portals');
insert into products (id, name, price, description) values (203, 'Jam - Raspberry', '$9.44', 'envisioneer scalable portals');
insert into products (id, name, price, description) values (204, 'Shrimp - Tiger 21/25', '$6.63', 'benchmark magnetic e-business');
insert into products (id, name, price, description) values (205, 'C - Plus, Orange', '$2.90', 'incubate back-end vortals');
insert into products (id, name, price, description) values (206, 'Chinese Foods - Cantonese', '$4.33', 'facilitate B2C systems');
insert into products (id, name, price, description) values (207, 'Blueberries - Frozen', '$7.07', 'mesh customized initiatives');
insert into products (id, name, price, description) values (208, 'Beer - Steamwhistle', '$6.50', 'leverage leading-edge infrastructures');
insert into products (id, name, price, description) values (209, 'Wine - Chardonnay South', '$2.42', 'leverage visionary users');
insert into products (id, name, price, description) values (210, 'Oats Large Flake', '$9.93', 'strategize interactive experiences');
insert into products (id, name, price, description) values (211, 'Ice Cream Bar - Hageen Daz To', '$4.19', 'exploit killer markets');
insert into products (id, name, price, description) values (212, 'Bread - Sour Sticks With Onion', '$7.46', 'enhance clicks-and-mortar interfaces');
insert into products (id, name, price, description) values (213, 'Mortadella', '$1.66', 'synergize cutting-edge interfaces');
insert into products (id, name, price, description) values (214, 'Oxtail - Cut', '$2.37', 'expedite scalable e-services');
insert into products (id, name, price, description) values (215, 'Cookies - Amaretto', '$5.84', 'incentivize out-of-the-box action-items');
insert into products (id, name, price, description) values (216, 'Wine - Red, Metus Rose', '$3.42', 'revolutionize cross-platform experiences');
insert into products (id, name, price, description) values (217, 'Flavouring Vanilla Artificial', '$5.06', 'optimize customized methodologies');
insert into products (id, name, price, description) values (218, 'Chocolate Bar - Smarties', '$7.93', 'envisioneer distributed infrastructures');
insert into products (id, name, price, description) values (219, 'Icecream - Dibs', '$8.13', 'innovate web-enabled e-markets');
insert into products (id, name, price, description) values (220, 'Gooseberry', '$6.76', 'empower next-generation schemas');
insert into products (id, name, price, description) values (221, 'Pasta - Cappellini, Dry', '$3.34', 'facilitate viral partnerships');
insert into products (id, name, price, description) values (222, 'Napkin - Beverge, White 2 - Ply', '$7.13', 'streamline end-to-end deliverables');
insert into products (id, name, price, description) values (223, 'Spice - Greek 1 Step', '$5.28', 'engineer wireless initiatives');
insert into products (id, name, price, description) values (224, 'Trout Rainbow Whole', '$9.52', 'strategize dot-com methodologies');
insert into products (id, name, price, description) values (225, 'Tea - Vanilla Chai', '$3.57', 'e-enable scalable partnerships');
insert into products (id, name, price, description) values (226, 'Flour - Corn, Fine', '$9.48', 'incentivize ubiquitous bandwidth');
insert into products (id, name, price, description) values (227, 'Shrimp - Baby, Warm Water', '$3.91', 'engage rich initiatives');
insert into products (id, name, price, description) values (228, 'Mushroom - White Button', '$7.61', 'reintermediate 24/365 systems');
insert into products (id, name, price, description) values (229, 'Stainless Steel Cleaner Vision', '$9.89', 'innovate web-enabled markets');
insert into products (id, name, price, description) values (230, 'Olive - Spread Tapenade', '$9.10', 'facilitate magnetic eyeballs');
insert into products (id, name, price, description) values (231, 'White Baguette', '$9.65', 'recontextualize cross-platform portals');
insert into products (id, name, price, description) values (232, 'Beans - Black Bean, Canned', '$1.88', 'recontextualize next-generation ROI');
insert into products (id, name, price, description) values (233, 'Wine - Toasted Head', '$5.01', 'leverage open-source applications');
insert into products (id, name, price, description) values (234, 'Pike - Frozen Fillet', '$6.46', 'seize interactive convergence');
insert into products (id, name, price, description) values (235, 'Salmon - Atlantic, No Skin', '$2.82', 'unleash strategic architectures');
insert into products (id, name, price, description) values (236, 'Wine - Chianti Classica Docg', '$1.75', 'exploit vertical deliverables');
insert into products (id, name, price, description) values (237, 'Potatoes - Peeled', '$1.86', 'e-enable robust experiences');
insert into products (id, name, price, description) values (238, 'Apple - Delicious, Red', '$7.74', 'disintermediate strategic infrastructures');
insert into products (id, name, price, description) values (239, 'Fenngreek Seed', '$6.65', 'seize value-added infrastructures');
insert into products (id, name, price, description) values (240, 'Wine - Blue Nun Qualitatswein', '$9.25', 'synergize best-of-breed users');
insert into products (id, name, price, description) values (241, 'Flower - Commercial Bronze', '$1.35', 'iterate killer solutions');
insert into products (id, name, price, description) values (242, 'Wine - White, Pinot Grigio', '$5.62', 'implement plug-and-play markets');
insert into products (id, name, price, description) values (243, 'Chilli Paste, Sambal Oelek', '$5.01', 'engage integrated paradigms');
insert into products (id, name, price, description) values (244, 'Scrubbie - Scotchbrite Hand Pad', '$8.08', 'mesh impactful content');
insert into products (id, name, price, description) values (245, 'Creme De Menthe Green', '$2.11', 'scale virtual portals');
insert into products (id, name, price, description) values (246, 'Chocolate Bar - Oh Henry', '$5.99', 'unleash bleeding-edge convergence');
insert into products (id, name, price, description) values (247, 'Coconut Milk - Unsweetened', '$2.19', 'envisioneer robust markets');
insert into products (id, name, price, description) values (248, 'Trout - Rainbow, Frozen', '$4.13', 'productize magnetic channels');
insert into products (id, name, price, description) values (249, 'Soup - Campbells Beef Strogonoff', '$5.11', 'embrace customized convergence');
insert into products (id, name, price, description) values (250, 'Glass Clear 8 Oz', '$4.84', 'expedite visionary eyeballs');
insert into products (id, name, price, description) values (251, 'Beef - Ground Medium', '$2.08', 'incentivize dynamic infomediaries');
insert into products (id, name, price, description) values (252, 'Lobster - Baby, Boiled', '$4.39', 'redefine collaborative e-commerce');
insert into products (id, name, price, description) values (253, 'Wiberg Super Cure', '$8.59', 'optimize sticky networks');
insert into products (id, name, price, description) values (254, 'Urban Zen Drinks', '$7.70', 'disintermediate enterprise architectures');
insert into products (id, name, price, description) values (255, 'Artichoke - Fresh', '$8.67', 'enhance killer technologies');
insert into products (id, name, price, description) values (256, 'Soup Campbells', '$6.56', 'reinvent B2C models');
insert into products (id, name, price, description) values (257, 'Nantucket - Orange Mango Cktl', '$6.90', 'synthesize transparent ROI');
insert into products (id, name, price, description) values (258, 'Wine - Red, Harrow Estates, Cab', '$3.97', 'leverage e-business web services');
insert into products (id, name, price, description) values (259, 'Sour Puss - Tangerine', '$9.86', 'reinvent clicks-and-mortar initiatives');
insert into products (id, name, price, description) values (260, 'Nantucket - Carrot Orange', '$6.29', 'integrate sticky eyeballs');
insert into products (id, name, price, description) values (261, 'Clams - Littleneck, Whole', '$5.53', 'target viral e-commerce');
insert into products (id, name, price, description) values (262, 'Container - Clear 32 Oz', '$3.77', 'incubate magnetic deliverables');
insert into products (id, name, price, description) values (263, 'Curry Paste - Madras', '$4.25', 'drive 24/7 web-readiness');
insert into products (id, name, price, description) values (264, 'Crawfish', '$6.18', 'implement vertical partnerships');
insert into products (id, name, price, description) values (265, 'Nut - Cashews, Whole, Raw', '$9.77', 'transform sexy e-tailers');
insert into products (id, name, price, description) values (266, 'Herb Du Provence - Primerba', '$8.91', 'harness bleeding-edge deliverables');
insert into products (id, name, price, description) values (267, 'Wine - Two Oceans Sauvignon', '$5.52', 'reintermediate seamless platforms');
insert into products (id, name, price, description) values (268, 'Eggs - Extra Large', '$7.39', 'extend intuitive channels');
insert into products (id, name, price, description) values (269, 'Bread - Bagels, Plain', '$8.43', 'deliver one-to-one e-business');
insert into products (id, name, price, description) values (270, 'Limes', '$4.24', 'engineer open-source solutions');
insert into products (id, name, price, description) values (271, 'Mix - Cappucino Cocktail', '$2.12', 'implement best-of-breed web-readiness');
insert into products (id, name, price, description) values (272, 'Rice - 7 Grain Blend', '$2.01', 'synthesize collaborative networks');
insert into products (id, name, price, description) values (273, 'Juice - Happy Planet', '$9.41', 'transform rich portals');
insert into products (id, name, price, description) values (274, 'Veal - Liver', '$6.04', 'revolutionize customized content');
insert into products (id, name, price, description) values (275, 'Soup Campbells Turkey Veg.', '$2.84', 'e-enable sticky schemas');
insert into products (id, name, price, description) values (276, 'Bag Stand', '$1.63', 'deploy holistic ROI');
insert into products (id, name, price, description) values (277, 'Coconut - Whole', '$2.22', 'empower proactive users');
insert into products (id, name, price, description) values (278, 'Crab - Meat', '$9.03', 'reinvent bricks-and-clicks e-business');
insert into products (id, name, price, description) values (279, 'Yogurt - Strawberry, 175 Gr', '$8.51', 'morph holistic functionalities');
insert into products (id, name, price, description) values (280, 'Pork - Back, Long Cut, Boneless', '$6.09', 'empower collaborative networks');
insert into products (id, name, price, description) values (281, 'Vegetable - Base', '$3.82', 'orchestrate granular action-items');
insert into products (id, name, price, description) values (282, 'Puree - Kiwi', '$7.55', 'deploy dot-com paradigms');
insert into products (id, name, price, description) values (283, 'Hold Up Tool Storage Rack', '$7.37', 'deploy user-centric functionalities');
insert into products (id, name, price, description) values (284, 'Sobe - Cranberry Grapefruit', '$2.06', 'drive real-time e-services');
insert into products (id, name, price, description) values (285, 'Wine - Cotes Du Rhone Parallele', '$6.69', 'evolve next-generation portals');
insert into products (id, name, price, description) values (286, 'Melon - Watermelon Yellow', '$8.09', 'disintermediate cutting-edge infrastructures');
insert into products (id, name, price, description) values (287, 'Sauce - Sesame Thai Dressing', '$7.82', 'embrace clicks-and-mortar solutions');
insert into products (id, name, price, description) values (288, 'Swiss Chard', '$8.34', 'whiteboard web-enabled ROI');
insert into products (id, name, price, description) values (289, 'Pastry - Baked Scones - Mini', '$7.74', 'drive sticky functionalities');
insert into products (id, name, price, description) values (290, 'Greens Mustard', '$1.94', 'synthesize clicks-and-mortar e-tailers');
insert into products (id, name, price, description) values (291, 'Soda Water - Club Soda, 355 Ml', '$5.76', 'engineer rich relationships');
insert into products (id, name, price, description) values (292, 'Cape Capensis - Fillet', '$4.36', 'unleash integrated solutions');
insert into products (id, name, price, description) values (293, 'Beer - Paulaner Hefeweisse', '$9.78', 'cultivate mission-critical experiences');
insert into products (id, name, price, description) values (294, 'Cherries - Bing, Canned', '$4.24', 'visualize clicks-and-mortar bandwidth');
insert into products (id, name, price, description) values (295, 'Truffle Cups - Brown', '$5.43', 'monetize granular content');
insert into products (id, name, price, description) values (296, 'Wine - Acient Coast Caberne', '$9.46', 'brand e-business deliverables');
insert into products (id, name, price, description) values (297, 'Longan', '$9.05', 'deploy user-centric relationships');
insert into products (id, name, price, description) values (298, 'Icecream - Dstk Strw Chseck', '$8.47', 'reinvent seamless action-items');
insert into products (id, name, price, description) values (299, 'Potatoes - Peeled', '$6.69', 'incubate revolutionary mindshare');
insert into products (id, name, price, description) values (300, 'Pasta - Lasagne, Fresh', '$6.02', 'embrace ubiquitous methodologies');
insert into products (id, name, price, description) values (301, 'Garbage Bags - Clear', '$8.81', 'target virtual functionalities');
insert into products (id, name, price, description) values (302, 'Flavouring - Orange', '$5.51', 'synergize web-enabled e-markets');
insert into products (id, name, price, description) values (303, 'Cheese - Parmigiano Reggiano', '$6.59', 'maximize integrated infrastructures');
insert into products (id, name, price, description) values (304, 'Halibut - Whole, Fresh', '$9.84', 'maximize innovative functionalities');
insert into products (id, name, price, description) values (305, 'Latex Rubber Gloves Size 9', '$5.24', 'deploy world-class architectures');
insert into products (id, name, price, description) values (306, 'Veal - Provimi Inside', '$4.70', 'brand B2C e-commerce');
insert into products (id, name, price, description) values (307, 'Pork - Inside', '$3.23', 'reinvent distributed infrastructures');
insert into products (id, name, price, description) values (308, 'Salmon Steak - Cohoe 6 Oz', '$2.85', 'mesh seamless technologies');
insert into products (id, name, price, description) values (309, 'Garbage Bags - Black', '$4.07', 'maximize cross-media e-tailers');
insert into products (id, name, price, description) values (310, 'Beer - Camerons Auburn', '$3.99', 'unleash value-added paradigms');
insert into products (id, name, price, description) values (311, 'Wine - Cava Aria Estate Brut', '$8.87', 'e-enable vertical users');
insert into products (id, name, price, description) values (312, 'Pasta - Cannelloni, Sheets, Fresh', '$5.92', 'generate extensible platforms');
insert into products (id, name, price, description) values (313, 'Bread - White, Unsliced', '$8.82', 'maximize viral e-markets');
insert into products (id, name, price, description) values (314, 'Cleaner - Pine Sol', '$6.98', 'revolutionize plug-and-play e-services');
insert into products (id, name, price, description) values (315, 'Compound - Mocha', '$2.19', 'redefine dynamic deliverables');
insert into products (id, name, price, description) values (316, 'Bagels Poppyseed', '$7.47', 'extend compelling web-readiness');
insert into products (id, name, price, description) values (317, 'Tomato - Green', '$9.16', 'unleash compelling partnerships');
insert into products (id, name, price, description) values (318, 'Salmon Steak - Cohoe 8 Oz', '$4.59', 'monetize 24/365 deliverables');
insert into products (id, name, price, description) values (319, 'Mushroom - Oyster, Fresh', '$8.37', 'transform bleeding-edge methodologies');
insert into products (id, name, price, description) values (320, 'Bread - Triangle White', '$1.32', 'exploit value-added metrics');
insert into products (id, name, price, description) values (321, 'Extract - Almond', '$6.07', 'envisioneer sexy mindshare');
insert into products (id, name, price, description) values (322, 'Southern Comfort', '$5.59', 'enhance 24/7 web-readiness');
insert into products (id, name, price, description) values (323, 'Beer - Blue', '$6.50', 'transition magnetic applications');
insert into products (id, name, price, description) values (324, 'Seabream Whole Farmed', '$7.32', 'benchmark enterprise infrastructures');
insert into products (id, name, price, description) values (325, 'Gatorade - Fruit Punch', '$1.86', 'whiteboard ubiquitous web-readiness');
insert into products (id, name, price, description) values (326, 'Jerusalem Artichoke', '$6.67', 'utilize cross-platform channels');
insert into products (id, name, price, description) values (327, 'Sugar - Palm', '$8.35', 'revolutionize one-to-one methodologies');
insert into products (id, name, price, description) values (328, 'Veal - Brisket, Provimi, Bone - In', '$5.05', 'e-enable interactive portals');
insert into products (id, name, price, description) values (329, 'Wine - Merlot Vina Carmen', '$3.98', 'repurpose turn-key methodologies');
insert into products (id, name, price, description) values (330, 'Wild Boar - Tenderloin', '$7.63', 'benchmark synergistic infomediaries');
insert into products (id, name, price, description) values (331, 'Cheese - Camembert', '$3.96', 'aggregate dynamic action-items');
insert into products (id, name, price, description) values (332, 'Chocolate - Sugar Free Semi Choc', '$9.16', 'productize killer eyeballs');
insert into products (id, name, price, description) values (333, 'Bread - Corn Muffaleta Onion', '$3.64', 'whiteboard value-added schemas');
insert into products (id, name, price, description) values (334, 'Tuna - Fresh', '$2.39', 'redefine global channels');
insert into products (id, name, price, description) values (335, 'Wine - Ruffino Chianti', '$4.39', 'drive world-class e-tailers');
insert into products (id, name, price, description) values (336, 'Strawberries', '$8.08', 'target cross-platform markets');
insert into products (id, name, price, description) values (337, 'Juice - Apple Cider', '$9.04', 'iterate open-source action-items');
insert into products (id, name, price, description) values (338, 'Chocolate Bar - Oh Henry', '$6.97', 'aggregate magnetic niches');
insert into products (id, name, price, description) values (339, 'Buffalo - Short Rib Fresh', '$6.31', 'monetize 24/365 partnerships');
insert into products (id, name, price, description) values (340, 'Cauliflower', '$5.85', 'generate robust models');
insert into products (id, name, price, description) values (341, 'Veal - Provimi Inside', '$9.17', 'cultivate mission-critical applications');
insert into products (id, name, price, description) values (342, 'Crab - Dungeness, Whole, live', '$9.25', 'evolve plug-and-play methodologies');
insert into products (id, name, price, description) values (343, 'Bread - White Mini Epi', '$1.68', 'recontextualize granular metrics');
insert into products (id, name, price, description) values (344, 'Wine - Kwv Chenin Blanc South', '$6.12', 'facilitate dot-com infomediaries');
insert into products (id, name, price, description) values (345, 'Wine - Montecillo Rioja Crianza', '$6.14', 'innovate synergistic vortals');
insert into products (id, name, price, description) values (346, 'Pastry - Banana Muffin - Mini', '$2.71', 'e-enable global initiatives');
insert into products (id, name, price, description) values (347, 'Beef Ground Medium', '$8.33', 'iterate compelling initiatives');
insert into products (id, name, price, description) values (348, 'Garbag Bags - Black', '$5.36', 'cultivate 24/7 relationships');
insert into products (id, name, price, description) values (349, 'Fond - Chocolate', '$6.43', 'transition turn-key infrastructures');
insert into products (id, name, price, description) values (350, 'Pear - Packum', '$8.66', 'strategize B2B markets');
insert into products (id, name, price, description) values (351, 'Kellogs All Bran Bars', '$9.96', 'architect strategic markets');
insert into products (id, name, price, description) values (352, 'Oyster - In Shell', '$1.53', 'redefine leading-edge convergence');
insert into products (id, name, price, description) values (353, 'Duck - Fat', '$3.46', 'deploy dynamic vortals');
insert into products (id, name, price, description) values (354, 'Sauce Bbq Smokey', '$1.20', 'reintermediate plug-and-play relationships');
insert into products (id, name, price, description) values (355, 'Broom And Broom Rack White', '$5.49', 'integrate integrated synergies');
insert into products (id, name, price, description) values (356, 'Foam Espresso Cup Plain White', '$4.58', 'transform real-time functionalities');
insert into products (id, name, price, description) values (357, 'Tea - Black Currant', '$5.88', 'scale B2B action-items');
insert into products (id, name, price, description) values (358, 'Momiji Oroshi Chili Sauce', '$3.64', 'disintermediate distributed ROI');
insert into products (id, name, price, description) values (359, 'Turnip - White', '$2.74', 'extend web-enabled deliverables');
insert into products (id, name, price, description) values (360, 'Pork - Sausage Casing', '$8.39', 'engineer open-source niches');
insert into products (id, name, price, description) values (361, 'Bread - Kimel Stick Poly', '$8.78', 'transform transparent methodologies');
insert into products (id, name, price, description) values (362, 'Wine - Magnotta - Bel Paese White', '$5.36', 'innovate rich infomediaries');
insert into products (id, name, price, description) values (363, 'Artichokes - Jerusalem', '$7.78', 'visualize cross-media interfaces');
insert into products (id, name, price, description) values (364, 'Sterno - Chafing Dish Fuel', '$2.71', 'incubate turn-key models');
insert into products (id, name, price, description) values (365, 'Thyme - Dried', '$3.10', 'architect B2C interfaces');
insert into products (id, name, price, description) values (366, 'Cheese - Bocconcini', '$3.37', 'incubate next-generation partnerships');
insert into products (id, name, price, description) values (367, 'Pepsi - Diet, 355 Ml', '$7.06', 'iterate vertical communities');
insert into products (id, name, price, description) values (368, 'Spice - Peppercorn Melange', '$1.52', 'deploy efficient solutions');
insert into products (id, name, price, description) values (369, 'Milk - Buttermilk', '$2.62', 'recontextualize strategic networks');
insert into products (id, name, price, description) values (370, 'Beans - Long, Chinese', '$9.53', 'e-enable cross-platform web-readiness');
insert into products (id, name, price, description) values (371, 'Tomatoes - Hot House', '$9.56', 'maximize integrated e-business');
insert into products (id, name, price, description) values (372, 'Wine - Jafflin Bourgongone', '$3.20', 'synergize sexy relationships');
insert into products (id, name, price, description) values (373, 'Jolt Cola', '$8.74', 'strategize granular metrics');
insert into products (id, name, price, description) values (374, 'Pasta - Fettuccine, Egg, Fresh', '$5.56', 'enable front-end networks');
insert into products (id, name, price, description) values (375, 'Bananas', '$4.14', 'syndicate frictionless supply-chains');
insert into products (id, name, price, description) values (376, 'Liqueur Banana, Ramazzotti', '$8.05', 'enhance mission-critical relationships');
insert into products (id, name, price, description) values (377, 'Sponge Cake Mix - Chocolate', '$9.08', 'empower leading-edge initiatives');
insert into products (id, name, price, description) values (378, 'Basil - Pesto Sauce', '$1.96', 'visualize cutting-edge schemas');
insert into products (id, name, price, description) values (379, 'Extract - Rum', '$1.15', 'morph collaborative synergies');
insert into products (id, name, price, description) values (380, 'Wine - Soave Folonari', '$6.74', 'innovate back-end mindshare');
insert into products (id, name, price, description) values (381, 'Oregano - Dry, Rubbed', '$3.34', 'seize bleeding-edge relationships');
insert into products (id, name, price, description) values (382, 'Rice - Jasmine Sented', '$4.81', 'synergize intuitive infomediaries');
insert into products (id, name, price, description) values (383, 'Parsley - Dried', '$4.47', 'architect leading-edge relationships');
insert into products (id, name, price, description) values (384, 'Water, Tap', '$7.14', 'enhance front-end action-items');
insert into products (id, name, price, description) values (385, 'Pork - Ham, Virginia', '$2.47', 'mesh out-of-the-box experiences');
insert into products (id, name, price, description) values (386, 'Wine - Ej Gallo Sonoma', '$9.81', 'revolutionize value-added e-business');
insert into products (id, name, price, description) values (387, 'Muffin - Mix - Strawberry Rhubarb', '$1.62', 'recontextualize impactful users');
insert into products (id, name, price, description) values (388, 'Lettuce - Treviso', '$3.34', 'redefine enterprise content');
insert into products (id, name, price, description) values (389, 'Shrimp - Black Tiger 6 - 8', '$8.58', 'synthesize bleeding-edge models');
insert into products (id, name, price, description) values (390, 'Flavouring - Rum', '$4.07', 'harness seamless metrics');
insert into products (id, name, price, description) values (391, 'Shrimp - 21/25, Peel And Deviened', '$4.48', 'e-enable interactive communities');
insert into products (id, name, price, description) values (392, 'Cheese - Brie,danish', '$2.30', 'monetize B2C supply-chains');
insert into products (id, name, price, description) values (393, 'Dried Peach', '$1.94', 'morph wireless deliverables');
insert into products (id, name, price, description) values (394, 'Chocolate - Pistoles, White', '$1.82', 'cultivate impactful action-items');
insert into products (id, name, price, description) values (395, 'Lemon Balm - Fresh', '$5.33', 'orchestrate extensible action-items');
insert into products (id, name, price, description) values (396, 'Wine - Red, Cooking', '$6.06', 'optimize clicks-and-mortar portals');
insert into products (id, name, price, description) values (397, 'Cheese - Brie Roitelet', '$8.57', 'scale mission-critical communities');
insert into products (id, name, price, description) values (398, 'Turnip - White', '$9.88', 'transform enterprise methodologies');
insert into products (id, name, price, description) values (399, 'Yoplait - Strawbrasp Peac', '$8.43', 'reintermediate bleeding-edge channels');
insert into products (id, name, price, description) values (400, 'Yogurt - Banana, 175 Gr', '$3.41', 'orchestrate strategic vortals');
insert into products (id, name, price, description) values (401, 'Iced Tea - Lemon, 340ml', '$2.38', 'facilitate vertical infomediaries');
insert into products (id, name, price, description) values (402, 'Vegetable - Base', '$9.51', 'deploy back-end e-business');
insert into products (id, name, price, description) values (403, 'Oven Mitts - 15 Inch', '$4.87', 'architect visionary systems');
insert into products (id, name, price, description) values (404, 'Tia Maria', '$5.44', 'syndicate world-class bandwidth');
insert into products (id, name, price, description) values (405, 'Longos - Grilled Salmon With Bbq', '$5.29', 'innovate value-added architectures');
insert into products (id, name, price, description) values (406, 'Sugar - Individual Portions', '$8.49', 'incentivize sticky initiatives');
insert into products (id, name, price, description) values (407, 'Apple - Custard', '$2.50', 'deliver distributed platforms');
insert into products (id, name, price, description) values (408, 'Juice - Ocean Spray Kiwi', '$9.12', 'syndicate innovative mindshare');
insert into products (id, name, price, description) values (409, 'Tequila - Sauza Silver', '$3.94', 'transition 24/365 metrics');
insert into products (id, name, price, description) values (410, 'Appetizer - Seafood Assortment', '$7.91', 'incubate real-time convergence');
insert into products (id, name, price, description) values (411, 'Bread - White Epi Baguette', '$7.68', 'syndicate compelling mindshare');
insert into products (id, name, price, description) values (412, 'Foie Gras', '$5.16', 'evolve clicks-and-mortar functionalities');
insert into products (id, name, price, description) values (413, 'Roe - White Fish', '$6.08', 'cultivate holistic platforms');
insert into products (id, name, price, description) values (414, 'Wine - Bourgogne 2002, La', '$8.99', 'incentivize efficient infomediaries');
insert into products (id, name, price, description) values (415, 'Table Cloth - 53x69 Colour', '$4.83', 'leverage distributed action-items');
insert into products (id, name, price, description) values (416, 'Roe - White Fish', '$3.83', 'reintermediate ubiquitous e-business');
insert into products (id, name, price, description) values (417, 'Soup - Knorr, Veg / Beef', '$3.75', 'reinvent e-business mindshare');
insert into products (id, name, price, description) values (418, 'Vol Au Vents', '$7.32', 'maximize integrated mindshare');
insert into products (id, name, price, description) values (419, 'Energy Drink Bawls', '$6.70', 'leverage 24/365 networks');
insert into products (id, name, price, description) values (420, 'Lemon Tarts', '$6.02', 'revolutionize plug-and-play web services');
insert into products (id, name, price, description) values (421, 'Tofu - Soft', '$6.91', 'productize distributed methodologies');
insert into products (id, name, price, description) values (422, 'Soup Campbells Beef With Veg', '$7.49', 'deploy magnetic methodologies');
insert into products (id, name, price, description) values (423, 'Duck - Whole', '$7.69', 'harness wireless partnerships');
insert into products (id, name, price, description) values (424, 'Wine - Rioja Campo Viejo', '$2.70', 'maximize 24/7 networks');
insert into products (id, name, price, description) values (425, 'Banana - Leaves', '$5.26', 'extend ubiquitous channels');
insert into products (id, name, price, description) values (426, 'Pasta - Canelloni', '$3.02', 'exploit vertical schemas');
insert into products (id, name, price, description) values (427, 'Thyme - Fresh', '$1.33', 'transform dot-com methodologies');
insert into products (id, name, price, description) values (428, 'Clam - Cherrystone', '$7.02', 'transition bricks-and-clicks relationships');
insert into products (id, name, price, description) values (429, 'Water - Mineral, Natural', '$2.15', 'embrace out-of-the-box markets');
insert into products (id, name, price, description) values (430, 'Tomato - Green', '$5.60', 'utilize user-centric niches');
insert into products (id, name, price, description) values (431, 'Energy Drink - Redbull 355ml', '$7.95', 'visualize viral systems');
insert into products (id, name, price, description) values (432, 'Mix - Cappucino Cocktail', '$3.69', 'repurpose interactive web-readiness');
insert into products (id, name, price, description) values (433, 'Sugar - Sweet N Low, Individual', '$8.94', 'target value-added architectures');
insert into products (id, name, price, description) values (434, 'Bread - White, Unsliced', '$9.71', 'extend open-source systems');
insert into products (id, name, price, description) values (435, 'Oil - Olive', '$6.45', 'facilitate value-added platforms');
insert into products (id, name, price, description) values (436, 'Flower - Daisies', '$5.12', 'transition web-enabled portals');
insert into products (id, name, price, description) values (437, 'Cheese - Goat', '$5.98', 'recontextualize interactive markets');
insert into products (id, name, price, description) values (438, 'Honey - Liquid', '$5.44', 'cultivate intuitive e-services');
insert into products (id, name, price, description) values (439, 'Coriander - Seed', '$2.24', 'seize bricks-and-clicks methodologies');
insert into products (id, name, price, description) values (440, 'Butter Balls Salted', '$7.01', 'orchestrate distributed infomediaries');
insert into products (id, name, price, description) values (441, 'Fork - Plastic', '$5.61', 'facilitate rich e-services');
insert into products (id, name, price, description) values (442, 'Rosemary - Primerba, Paste', '$8.70', 'empower open-source schemas');
insert into products (id, name, price, description) values (443, 'Horseradish Root', '$5.82', 'engage synergistic markets');
insert into products (id, name, price, description) values (444, 'Lamb - Sausage Casings', '$7.47', 'recontextualize synergistic e-markets');
insert into products (id, name, price, description) values (445, 'Beer - Original Organic Lager', '$6.66', 'streamline collaborative solutions');
insert into products (id, name, price, description) values (446, 'Soup - Base Broth Beef', '$6.77', 'architect holistic solutions');
insert into products (id, name, price, description) values (447, 'Puree - Guava', '$9.59', 'engineer mission-critical methodologies');
insert into products (id, name, price, description) values (448, 'Cake - Box Window 10x10x2.5', '$7.38', 'architect end-to-end partnerships');
insert into products (id, name, price, description) values (449, 'Lettuce - Curly Endive', '$2.40', 'revolutionize intuitive functionalities');
insert into products (id, name, price, description) values (450, 'Olives - Morracan Dired', '$4.60', 'engineer global schemas');
insert into products (id, name, price, description) values (451, 'Mushroom - Porcini, Dry', '$1.20', 'iterate rich paradigms');
insert into products (id, name, price, description) values (452, 'Wasabi Powder', '$3.04', 'e-enable innovative web services');
insert into products (id, name, price, description) values (453, 'Plate Foam Laminated 9in Blk', '$1.15', 'transition viral niches');
insert into products (id, name, price, description) values (454, 'Icecream Bar - Del Monte', '$9.25', 'synergize dynamic initiatives');
insert into products (id, name, price, description) values (455, 'Turnip - Wax', '$6.42', 'redefine compelling platforms');
insert into products (id, name, price, description) values (456, 'Goat - Whole Cut', '$5.61', 'matrix cutting-edge schemas');
insert into products (id, name, price, description) values (457, 'Wine - Vovray Sec Domaine Huet', '$1.61', 'deploy one-to-one ROI');
insert into products (id, name, price, description) values (458, 'Beef - Eye Of Round', '$4.96', 'generate collaborative portals');
insert into products (id, name, price, description) values (459, 'Wine - Guy Sage Touraine', '$9.24', 'drive dynamic partnerships');
insert into products (id, name, price, description) values (460, 'Grouper - Fresh', '$6.29', 'incubate value-added methodologies');
insert into products (id, name, price, description) values (461, 'Bread - Malt', '$9.82', 'empower dot-com synergies');
insert into products (id, name, price, description) values (462, 'Shrimp - 21/25, Peel And Deviened', '$7.15', 'leverage vertical markets');
insert into products (id, name, price, description) values (463, 'Oil - Margarine', '$9.32', 'incentivize killer e-commerce');
insert into products (id, name, price, description) values (464, 'Figs', '$1.84', 'enhance one-to-one portals');
insert into products (id, name, price, description) values (465, 'Cocoa Powder - Natural', '$7.66', 'exploit impactful deliverables');
insert into products (id, name, price, description) values (466, 'Cleaner - Pine Sol', '$9.02', 'streamline bricks-and-clicks deliverables');
insert into products (id, name, price, description) values (467, 'Munchies Honey Sweet Trail Mix', '$3.52', 'repurpose synergistic niches');
insert into products (id, name, price, description) values (468, 'Irish Cream - Butterscotch', '$9.16', 'benchmark cross-platform interfaces');
insert into products (id, name, price, description) values (469, 'Octopus', '$4.21', 'synergize cross-platform metrics');
insert into products (id, name, price, description) values (470, 'Wine - Vovray Sec Domaine Huet', '$7.38', 'seize cross-platform e-tailers');
insert into products (id, name, price, description) values (471, 'Capers - Pickled', '$9.50', 'visualize integrated applications');
insert into products (id, name, price, description) values (472, 'Wine - Ej Gallo Sierra Valley', '$7.24', 'empower web-enabled channels');
insert into products (id, name, price, description) values (473, 'Triple Sec - Mcguinness', '$8.33', 'reinvent scalable infrastructures');
insert into products (id, name, price, description) values (474, 'Pants Custom Dry Clean', '$7.74', 'innovate dot-com networks');
insert into products (id, name, price, description) values (475, 'Yogurt - Cherry, 175 Gr', '$3.76', 'redefine collaborative niches');
insert into products (id, name, price, description) values (476, 'Red Currant Jelly', '$7.87', 'matrix global users');
insert into products (id, name, price, description) values (477, 'Lemon Balm - Fresh', '$4.28', 'seize enterprise ROI');
insert into products (id, name, price, description) values (478, 'Gelatine Leaves - Envelopes', '$4.51', 'extend dot-com infrastructures');
insert into products (id, name, price, description) values (479, 'Knife Plastic - White', '$6.48', 'incubate rich users');
insert into products (id, name, price, description) values (480, 'Wine - White, Riesling, Semi - Dry', '$2.37', 'incentivize bleeding-edge networks');
insert into products (id, name, price, description) values (481, 'Shrimp - Black Tiger 8 - 12', '$6.50', 'aggregate integrated e-markets');
insert into products (id, name, price, description) values (482, 'Wine - Red, Concha Y Toro', '$8.12', 'enable extensible synergies');
insert into products (id, name, price, description) values (483, 'Salt And Pepper Mix - Black', '$8.22', 'evolve killer web-readiness');
insert into products (id, name, price, description) values (484, 'The Pop Shoppe - Lime Rickey', '$5.39', 'streamline distributed e-business');
insert into products (id, name, price, description) values (485, 'Juice - Orange 1.89l', '$2.53', 'repurpose innovative e-business');
insert into products (id, name, price, description) values (486, 'Truffle Shells - White Chocolate', '$3.46', 'matrix synergistic solutions');
insert into products (id, name, price, description) values (487, 'Bar Mix - Lemon', '$1.93', 'monetize enterprise applications');
insert into products (id, name, price, description) values (488, 'Thyme - Fresh', '$1.41', 'revolutionize killer markets');
insert into products (id, name, price, description) values (489, 'Cheese - Brie', '$1.42', 'matrix best-of-breed communities');
insert into products (id, name, price, description) values (490, 'Sugar - Cubes', '$10.00', 'extend one-to-one initiatives');
insert into products (id, name, price, description) values (491, 'Pineapple - Canned, Rings', '$4.11', 'e-enable rich mindshare');
insert into products (id, name, price, description) values (492, 'Water - San Pellegrino', '$8.23', 'facilitate turn-key deliverables');
insert into products (id, name, price, description) values (493, 'Appetizer - Cheese Bites', '$7.67', 'repurpose end-to-end architectures');
insert into products (id, name, price, description) values (494, 'Hot Chocolate - Individual', '$2.01', 'reintermediate seamless communities');
insert into products (id, name, price, description) values (495, 'Lemon Grass', '$5.16', 'transition impactful infrastructures');
insert into products (id, name, price, description) values (496, 'Sauce - Salsa', '$8.77', 'implement global infrastructures');
insert into products (id, name, price, description) values (497, 'Wine - Acient Coast Caberne', '$7.62', 'extend strategic platforms');
insert into products (id, name, price, description) values (498, 'Turkey - Ground. Lean', '$9.04', 'orchestrate rich e-tailers');
insert into products (id, name, price, description) values (499, 'Olives - Stuffed', '$2.65', 'embrace next-generation infomediaries');
insert into products (id, name, price, description) values (500, 'Kippers - Smoked', '$1.58', 'aggregate world-class vortals');